name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --output-on-failure --build-config Release

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/bin
